import streamlit as st

 # python -m streamlit run app.py

st.title("plalyst da Aline")
genero_musical=["Samba", "Gospel", "pop", "Sertanejo"]
# Dicionário relacionando gêneros as minhas músicas
musica_por_genero= {
    "Samba": ["Instinto Cantores", "Sorriso Maroto", "Menos é Mais"],
    "Gospel": ["Priscilla-Alcantara", "Julia Vitória", "Isadora Pompeo"],
    "pop": ["Ed Sheeran" ,  "Miley Cyrus","Bruno Mars", "Michael Jackson"],
    "Sertanejo": ["simone", "Mari Fernandez", "Ana castela"]
}
# Selectbox para escolher o gênero   
genero_selecionado = st.sidebar.selectbox("Selecione o gênero:", genero_musical)
# Selectbox para escolher a música (apenas do gênero selecionado)
if genero_selecionado:
     musica_por_genero= st.sidebar.selectbox(
        "Selecione o Artista:", 
        musica_por_genero[genero_selecionado]
    )
# Mostrar apenas a música selecionada 
if genero_selecionado and musica_por_genero:
    st.write(f"**Artista Selecionado:** {musica_por_genero}")
    st.write(f"**Gênero:** {genero_selecionado}")
    st.image(f"{musica_por_genero}.png")

# ----------------------------------------------------------------

if genero_selecionado=='Samba' and musica_por_genero=='Instinto Cantores':
    st.markdown("---")
    st.markdown("O cantor da música Instinto é Gamadinho. Sua trajetória musical começou nas rodas de samba da Baixada Fluminense, no Rio de Janeiro, e ele se destacou como um dos nomes da nova safra do pagode carioca. A carreira de Gamadinho Nome artístico e origem: Gamadinho é o nome artístico de Felipe Ribeiro. Ele iniciou sua carreira musical ainda adolescente, aos 14 anos, cantando e tocando samba na sua região de origem. The Voice Brasil: O cantor participou do programa de televisão The Voice Brasil 2, que ajudou a dar mais visibilidade à sua carreira. Sucessos e álbuns: Além de Instinto, outros de seus sucessos incluem músicas como Por Favor e Chá de Sumiço. Em 2023, ele lançou o seu primeiro DVD, Pra ficar. Virada com a música Instinto: Embora Instinto tenha sido gravada alguns anos antes, sua projeção nacional decolou após um vídeo viral em que ele aparece cantando a música com sua filha. A naturalidade e emoção da cena fizeram com que a canção se tornasse um grande sucesso nas redes sociais, com mais de 20 milhões de visualizações no YouTube e milhares de compartilhamentos no Instagram. Trabalhos recentes: Gamadinho continua ativo no cenário musical, participando de projetos como o Respeita Minha História 4, da rádio FM O Dia, e realizando shows pelo país.")

elif genero_selecionado=='Samba' and musica_por_genero=='Sorriso Maroto':
    st.markdown("---")
    st.markdown("O Sorriso Maroto é um dos grupos de pagode mais populares e duradouros do Brasil, com uma trajetória de sucesso que começou em 1997 no bairro do Grajaú, no Rio de Janeiro. Conhecido por suas canções românticas e animadas, o grupo conquistou milhões de fãs ao longo de quase três décadas de carreira. Integrantes A formação do grupo é a seguinte: Bruno Cardoso: Vocalista. Sérgio Jr.: Violonista.Cris Oliveira: Pandeiro e reco-reco.Vinícius Augusto: Tecladista.Fred Araújo: Percussão. Principais músicas Com uma vasta discografia, o Sorriso Maroto é responsável por diversos sucessos que marcaram gerações no pagode. Algumas de suas canções mais conhecidas incluem Futuro Prometido, Estrela Maior, Coração Deserto, Me Olha Nos Olhos, Em Suas Mãos, Cadê Você, É Diferente, Não Mereço Ser Amante, Amanhã, Sinais e Fica Combinado Assim.  Momentos marcantes O grupo é conhecido por suas apresentações ao vivo energéticas. A turnê Sorriso As Antigas em 2024 teve um show memorável no Estádio do Maracanã, que recebeu mais de 60 mil pessoas. Esta turnê gerou um álbum ao vivo, gravado em diversas cidades. Em 2025, o Sorriso Maroto gravou no famoso Abbey Road Studios, em Londres, o terceiro volume do projeto Sorriso Eu Gosto - No Pagode. Este projeto é uma homenagem ao grupo Fundo de Quintal, com novas versões de suas músicas")

elif genero_selecionado=='Samba' and musica_por_genero=='Menos é Mais':
    st.markdown("---")
    st.markdown("A banda Menos é Mais é um grupo de pagode de Brasília que ganhou destaque no Brasil pelo jeito descontraído de cantar e pelos medleys que fazem sucesso no YouTube. Eles são conhecidos por dar uma cara nova ao pagode, misturando clássicos do gênero com músicas atuais. Uma das músicas mais famosas deles é “Vai Me Dando Corda”, que conquistou bastante público e ajudou a firmar a banda no cenário nacional.")

elif genero_selecionado=='Gospel' and musica_por_genero=='Priscilla-Alcantara':
    st.markdown("---")
    st.markdown("Priscilla-Alcantara sobre ela e suas melhores musicas Priscilla Alcantara, agora conhecida apenas como Priscilla, é uma cantora, compositora e apresentadora que iniciou sua carreira na infância e passou por uma notável transição do cenário gospel para a música pop. A mudança de estilo musical e visual marcou uma nova fase em sua trajetória profissional, consolidada a partir de 2021.  Sobre Priscilla ,Carreira na TV: Priscilla ficou conhecida do público por apresentar o programa infantil Bom Dia & Companhia, no SBT, ao lado de Yudi Tamashiro, entre 2005 e 2013. Período gospel: Após deixar a TV, ela se dedicou à carreira musical, tornando-se um dos grandes nomes da música gospel, também chamada por ela de pop cristão. Lançou álbuns como Até Sermos Um 2015 e Gente 2018, conquistando uma grande legião de fãs. Transição para o pop: Em 2021, depois de vencer a primeira temporada do The Masked Singer Brasil, ela lançou o álbum Você Aprendeu a Amar?. A partir de 2023, reforçou a transição para o pop, abandonando o sobrenome Alcantara e adotando um novo visual com cabelos vermelhos. A artista afirma que a mudança reflete um crescimento pessoal e uma busca por liberdade artística.  Melhores músicas A carreira de Priscilla é dividida em duas fases musicais distintas, com sucessos em ambos os estilos.  Melhores músicas da era gospel: Girassol part. Whindersson Nunes: Uma das suas canções gospel mais populares, que se tornou um sucesso estrondoso na internet. Espírito Santo: Uma balada emocionante que se destaca por sua interpretação vocal. Me Refez: Com um estilo mais pop dentro do gospel, a música foi a primeira do gênero cristão brasileiro a entrar no Top 200 global do Spotify em 2018. Liberdade: Canção que, mesmo na fase gospel, já abordava temas de libertação, como uma prévia de sua transição artística.  Melhores músicas da era pop: Você Aprendeu a Amar: Faixa-título de seu primeiro álbum pop 2021, que marca a virada na carreira da artista. Quer Dançar part. Bonde do Tigrão: Lançada em 2023, essa parceria com o Bonde do Tigrão foi um marco na transição de Priscilla para o pop, causando impacto nas redes sociais. Boyzinho: Com uma batida mais dançante e ousada, a música foi lançada em 2021 e explora temas de romance. Correntes: Outro destaque do álbum Você Aprendeu a Amar, a canção explora as desilusões amorosas e o fim de relacionamentos. ")

elif genero_selecionado=='Gospel' and musica_por_genero=='Julia Vitória':
    st.markdown("---")
    st.markdown("Julia Vitória sobre suas melhores musicas Julia Vitória é uma das maiores revelações da música gospel, conhecida por sua voz potente e composições que expressam sua fé de forma íntima e profunda. Começando sua carreira ainda na adolescência com covers na internet, ela rapidamente se tornou um fenômeno com milhões de visualizações e ouvintes nas plataformas de streaming.  Confira algumas de suas melhores músicas: 1. De Dentro Pra Fora ,Um dos singles mais conhecidos de Julia Vitória, que a lançou para a fama em 2018. A música foi fruto de uma oração pessoal da cantora, e sua letra expressa o desejo por uma transformação interior e genuína. A canção conquistou o público e se tornou um dos seus maiores sucessos.  2. Tua Presença, Lançada em 2023, esta música de adoração foi gravada ao vivo e é uma das favoritas do público. A canção exalta a centralidade de Deus e a satisfação encontrada em Sua presença, com uma letra emocionante e a performance marcante da cantora.  3. Esperança, (feat. Gabriel Guedes) Parte do álbum homônimo de 2020, Esperança, é uma colaboração com Gabriel Guedes. A música traz uma mensagem de conforto e confiança em Deus, e se tornou um hit por sua melodia inspiradora e a bela sintonia entre os dois vocalistas.  4. Além do Rio Azul, Uma releitura do clássico do grupo Voz da Verdade, esta versão na voz de Julia Vitória (com participação de Lukas Agustinho em uma das versões) ganhou enorme popularidade. A música fala sobre a esperança da vida eterna e emocionou muitos fãs.  5. Começo, Meio e Fim Lançada em 2021, esta canção se tornou um dos grandes sucessos de Julia. A música celebra a soberania e a fidelidade de Deus em todas as fases da vida, desde o início até o fim.  6. Tuas Águas, feat. Gabriela Rocha Uma parceria poderosa com a também renomada cantora gospel Gabriela Rocha. A canção é uma oração por renovação e cura, onde as águas de Deus representam o poder purificador e restaurador do Espírito Santo.  7. Nós Te Adoramos, Gravada ao vivo, essa música de adoração ressalta a majestade de Deus e a adoração que Ele merece. Com a forte interpretação vocal de Julia Vitória, a canção é um convite à reverência e ao louvor.  As respostas da IA podem conter erros. Saiba mais undefined undefined undefined 15 sites  Julia Vitoria - Nós Te Adoramos Ao Vivo - YouTube Feb 9, 2023 — Entre os singles mais conhecidos de Julia estão: “Começo, Meio e Fim”, “De Dentro Pra Fora”, Esperança” e a releitura de Além do Rio Azul, do grupo@VozdaVe... favicon YouTube Julia Vitoria - Palavras Clipe Oficial - YouTube Nov 30, 2022 — Entre os singles mais conhecidos de Julia Vitória, além dos já mencionados, estão: “De Dentro Pra Fora”, “Tuas Águas”, com GabrielaRochaOficial, Começo, Mei... favicon YouTube ,Julia Vitória  Wikipédia, a enciclopédia livre A Julia Vitoria começou a carreira aos 15 anos quando postava covers de músicas gospels e é contratada pela Musile Records . As músicas da cantora Julia Vitória... favicon Wikipedia")

elif genero_selecionado=='Gospel' and musica_por_genero=='Isadora Pompeo':
    st.markdown("---")
    st.markdown("Isadora Pompeo, uma das vozes mais populares da música gospel brasileira, foca suas canções em temas de fé, superação, adoração e relacionamento pessoal com Deus. Sua discografia, que inclui covers e músicas autorais, busca especialmente conectar-se com o público jovem.  Resumo temático das músicas: Busca e encontro com o divino: Muitas de suas músicas, como Minha Morada e Oi, Jesus, expressam uma profunda busca pela presença de Deus, apresentada como o único refúgio e o verdadeiro lar. Superação e esperança: Em canções como História e  Processo, Isadora aborda a vulnerabilidade humana e a fé para superar momentos difíceis. A mensagem é de que o choro pode durar uma noite, mas a esperança e a paz vêm pela manhã, como visto em Resultado. Ela também relata como a fé a ajudou a lidar com a depressão. Dependência e entrega: A rendição total a Deus é um tema central. Em Canção de Paulo, ela descreve a transformação e a entrega à vontade divina. Já em Ovelhinha, a letra fala da busca por redenção e da necessidade de se encontrar em Deus, mesmo diante das falhas. Amor incondicional de Deus: Músicas como Você Não Cansa destacam o amor e a paciência de Deus, que acolhe e perdoa, independentemente das falhas humanas. A ideia de que Deus é um refúgio seguro é recorrente. Gratidão e reconhecimento: Em faixas como Bênçãos Que Não Têm Fim, Isadora canta sobre a gratidão pelas bênçãos diárias e o reconhecimento da fidelidade de Deus. Adoração e reverência: Louvores como Palavras e Palavras e O Nome de Jesus focam na adoração e na exaltação de Deus, expressando a dificuldade de descrever plenamente a Sua grandeza. Músicas notáveis:Hey, Pai: Um de seus primeiros grandes sucessos, que marcou o início de sua visibilidade nacional em 2017. Minha Morada: Lançada em 2017, é uma das canções mais populares, com uma mensagem de encontrar refúgio em Deus. Processo: Música de seu álbum homônimo de 2021, onde Isadora aborda sua luta contra a depressão e a jornada de fé para superá-la. Bênçãos Que Não Têm Fim: Lançada em 2023, a música fez de Isadora a primeira cantora gospel a alcançar o Top 10 da Billboard Brasil. ")

elif genero_selecionado=='pop' and musica_por_genero=='Ed Sheeran':
    st.markdown("---")
    st.markdown("Thinking Out Loud  Tema: Um amor que envelhece e se mantém ao longo do tempo. Significado: A música é uma reflexão sobre a fidelidade e o amor duradouro. A letra fala sobre amar a pessoa mesmo na velhice, quando a beleza e a juventude se esvaem, e a memória pode falhar. Contexto: Conhecida como uma canção romântica e popular em casamentos, foi inspirada no relacionamento de Sheeran com Athina Andrelos, na época em que a música foi escrita.  2. Perfect Tema: Um amor ideal e reconectado. Significado: A letra descreve um amor que se reencontra e amadurece, superando o tempo e as mudanças. A canção foi inspirada na esposa de Sheeran, Cherry Seaborn, que ele conheceu na escola e reencontrou anos depois. Contexto: Lançada em 2017, Perfect rapidamente se tornou um hino de amor, sendo frequentemente escolhida por casais para cerimônias de casamento e se tornando um dos maiores sucessos do artista.  3. Shivers Tema: Intensa paixão e desejo por alguém especial. Significado: Diferente das baladas mais lentas, Shivers é uma música pop animada e vibrante. A letra expressa a sensação de arrepios e o efeito elétrico que a pessoa amada provoca. Contexto: Lançada em 2021 no álbum =, a faixa tem uma energia dançante e positiva. O videoclipe mostra Sheeran assumindo diferentes personagens para conquistar a amada, reforçando a ideia do desejo de reinventar-se e impressioná-la. ")

elif genero_selecionado=='pop' and musica_por_genero=='Miley Cyrus':
    st.markdown("---")
    st.markdown(" Miley Cyrus, há uma confusão na estrutura, pois você solicita informações sobre uma música de outro cantor e duas músicas dela. A seguir, um resumo da música de Bruno Mars que supostamente inspirou Flowers e, em seguida, as duas canções de Miley.  Música de cantor: When I Was Your Man (Bruno Mars) Significado: Lançada em 2013, a canção é uma balada emocional em que o cantor Bruno Mars lamenta o fim de um relacionamento e a maneira como tratou sua ex-parceira. A letra expressa arrependimento e a esperança de que o novo parceiro da mulher a trate melhor do que ele próprio o fez. Relação com Miley: Muitos fãs e a mídia teorizam que a música de Bruno Mars serviu de inspiração para Flowers. Isso porque a letra de Miley responde diretamente a vários versos, sugerindo que ela pode se dar as flores e se tratar melhor do que foi tratada.  Música de Miley Cyrus: Flowers  Destaque: O single se tornou um sucesso global, vencendo dois prêmios Grammy e quebrando recordes de streamings, solidificando a fase atual da artista.  Música de Miley Cyrus: Wrecking Ball Significado: Lançada em 2013, a música é uma balada intensa que aborda a dor avassaladora de um relacionamento e a incapacidade de superá-lo. A letra descreve a sensação de ser destruído emocionalmente e de ter o coração partido. Destaque: Wrecking Ball é uma das músicas mais icônicas de Miley. O videoclipe causou polêmica na época por seu conteúdo explícito e o simbolismo da bola de demolição, mas a música em si é um clássico moderno. ")

elif genero_selecionado=='pop' and musica_por_genero=='Bruno Marss':
    st.markdown("---")
    st.markdown("Bruno Mars é um cantor e compositor havaiano, famoso pelo estilo versátil que mistura pop, soul, R&B e funk. Ele começou a se destacar em 2010 e, desde então, conquistou o mundo com hits dançantes e também com músicas românticas. A canção que muita gente considera a melhor dele é “Uptown Funk”, feita em parceria com Mark Ronson. Ela virou um fenômeno mundial, estourou nas paradas e até hoje é lembrada por seu ritmo animado, cheio de groove e energia, que faz qualquer um querer dançar.")

elif genero_selecionado=='pop' and musica_por_genero==' Michael Jackson':
    st.markdown("---")
    st.markdown("Michael Jackson foi um cantor, compositor e dançarino americano, conhecido como o “Rei do Pop”. Ele revolucionou a música com seu estilo inovador, videoclipes criativos e passos de dança marcantes, como o moonwalk. Ao longo da carreira, vendeu milhões de discos e influenciou artistas do mundo todo. A música que muita gente considera a melhor dele é Thriller, que não só foi um grande sucesso musical, como também ganhou um clipe icônico, cheio de efeitos e coreografia que até hoje é lembrada.")

elif genero_selecionado=='Sertanejo' and musica_por_genero=='simone':
    st.markdown("---")
    st.markdown("Simaria são uma dupla sertaneja brasileira, também chamadas de as coleguinhas. Elas começaram a carreira cantando em bandas de forró, mas ganharam fama nacional no sertanejo com músicas animadas e cheias de sofrência. Ficaram conhecidas pelo carisma no palco e pela força da parceria como irmãs.Uma das músicas mais famosas e consideradas das melhores delas é Meu Violão e o Nosso Cachorro, que marcou a carreira da dupla e caiu no gosto do público por falar de amor e separação de um jeito simples e emocionante.")

elif genero_selecionado=='Sertanejo' and musica_por_genero=='Mari Fernandez':
   st.markdown("---")
   st.markdown("é uma cantora e compositora cearense, considerada uma das vozes mais fortes da nova geração do piseiro e forró romântico. Ela começou a estourar em 2021 e logo ganhou espaço nacional com músicas que misturam sofrência e batidas dançantes.Entre as melhores músicas dela, podemos destacar:Não, Não Vou que virou viral nas redes sociais; Eu Gosto Assim com Felipe Amorim; Parada Louca; Ficante Fiel. Ela se destaca por letras que falam de amor, curtição e liberdade, sempre com uma batida animada que conquista os fãs.")

elif genero_selecionado=='Sertanejo' and musica_por_genero=='Ana castela':
   st.markdown("---")
   st.markdown("Ana Castela é uma cantora brasileira que ficou conhecida como a boiadeira, porque mistura o sertanejo com o estilo agro e tem uma identidade bem ligada ao campo. Ela começou a fazer sucesso em 2021 e logo conquistou o público jovem com sua voz marcante e jeito autêntico.Algumas das melhores músicas dela são:Pipoco com Melody e DJ Chris no Beat, que virou hit nacional;Solteiro Forçado; Boiadeira;Nosso Quadro.Ela se destaca por trazer um sertanejo moderno, com pegada animada, mas também com músicas românticas que marcaram sua carreira.")
